---
title: "Climate changes project"
author: "Paul Markus and Withee Poositasai"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```

# The dataset

## 1.Global land temperature data by country

Source: <https://data.world/data-society/global-climate-change-data>

```{r}
temperature <- read_csv('GlobalLandTemperatures_GlobalLandTemperaturesByCountry.csv', show_col_types = FALSE)
glimpse(temperature)
```

Check the datetime column. The newest record is in 2013-09-01. The dataset contains record of every 1st of the month.

```{r}
sort(unique(temperature$dt), decreasing = TRUE)[1:10]
```

```{r}
temperature %>%
  filter(between(dt, as.Date('2002-01-01'), as.Date('2012-12-31'))) %>%
  filter(Country %in% c('Estonia', 'Thailand', 'Africa', 'Australia', 'United States', 'China', 'India')) %>%
  ggplot(aes(x=dt, y=AverageTemperature, color=Country)) +
    geom_line() +
    labs(title = 'Monthly average temperature from 2002-2012')
```

Calculate annual average temperature from 1990 - 2012 and drop NAs row

```{r}
annualTemperature <- temperature %>%
  drop_na %>%
  mutate(Year = as.integer(format(dt, '%Y'))) %>%
  select(-dt) %>%
  filter(between(Year, 1900, 2022)) %>%
  group_by(Country, Year) %>%
  summarise(AverageTemperature = mean(AverageTemperature), AverageTemperatureUncertainty = mean(AverageTemperatureUncertainty))

annualTemperature
```

```{r}
annualTemperature %>%
  filter(Country %in% c('Estonia', 'Thailand', 'Africa', 'Australia', 'United States', 'China', 'India')) %>%
  ggplot(aes(x=Year, y=AverageTemperature, color=Country)) +
    geom_line() +
    labs(title = 'Annual average temperature from 1900 - 2012')
```

```{r}
annualTemperature %>%
  filter(Country %in% c('Estonia', 'Thailand', 'Africa', 'Australia', 'United States', 'China', 'India')) %>%
  ggplot(aes(x=Year, y=AverageTemperature, color=Country)) +
    geom_point(size = 0.8, alpha = 0.3) +
    geom_smooth(method='lm') +
    labs(title = 'Annual average temperature from 1900 - 2012')
```

## 2. Global CO2 emission by country

Source: <https://ourworldindata.org/co2-dataset-sources>

```{r}
co2emission <- read_csv('annual-co2-emissions-per-country.csv', show_col_types = FALSE)
glimpse(co2emission)
```
Check the year column. The dataset contain annual data. The newest record is in 2021

```{r}
sort(unique(co2emission$Year), decreasing = TRUE)[1:10]
```

Filter only record from 1900-2012

```{r}
co2emission %>%
  filter(between(Year, 1900, 2012))
```
```{r}
co2emission %>%
  filter(between(Year, 1900, 2012)) %>%
  filter(Entity %in% c('Estonia', 'Thailand', 'Africa', 'Australia', 'United States', 'China', 'India')) %>%
  ggplot(aes(x=Year, y=`Annual CO2 emissions`, color=Entity)) +
    geom_line() +
    labs(title = 'Annual CO2 emissions from 1900-2012')
```
