name: Render and publish rmarkdown

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render HTML output
        run: Rscript -e 'rmarkdown::render("notebook.Rmd", output_dir="dist", output_file="index")'
      - name: Deploy to Github Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
